dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
  - npm run build
